### ISSUE TITLE
Blank lines for paragraph and page breaks should be stripped first

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/Studio-Web-archived#14]
Our format defines a blank line is a paragraph break, and two blank lines is a page break. Right now, though, if there is any whitespace on the line, it would *not* be recognized as a blank line. That's poor UX since users will not visually see why their paragraph or page breaks don't work.

The change actually needs to be done in Studio, in `align.py` / `create_tei_from_text()` but I'm documenting it here as an issue because of its UX impact on Studio-Web.

**Comment by dhdaines** [comment]
I think you meant to say "if there is any whitespace ... it *wouldn't* be recognized as a blank line"?

**Comment by joanise** [comment]
Yeah, indeed. :) Let me fix that in the original comment, it makes no sense as originally written. Thanks for the catch!
